# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-27 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_url', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('summary', models.CharField(max_length=1280)),
                ('action_type', models.CharField(max_length=12)),
            ],
        ),
    ]
